// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDNhhQ-222oXE_9KPFPQj2WRAKCybJlUFw',
//     appId: '1:157706479340:web:ce7e5ba18f297cc222a7c9',
//     messagingSenderId: '157706479340',
//     projectId: 'growth-26879',
//     authDomain: 'growth-26879.firebaseapp.com',
//     storageBucket: 'growth-26879.firebasestorage.app',
//     measurementId: 'G-PNW1FW7PQB',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBsNeza0eHacn8Vg3pKyLh33a_QWdVcjSY',
//     appId: '1:157706479340:android:b25d66aebf68180222a7c9',
//     messagingSenderId: '157706479340',
//     projectId: 'growth-26879',
//     storageBucket: 'growth-26879.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAHsLqFmLS_kWQwoNLw8_qdumUEW38kj3c',
//     appId: '1:157706479340:ios:1f0136ba041d971722a7c9',
//     messagingSenderId: '157706479340',
//     projectId: 'growth-26879',
//     storageBucket: 'growth-26879.firebasestorage.app',
//     iosBundleId: 'com.example.growth',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAHsLqFmLS_kWQwoNLw8_qdumUEW38kj3c',
//     appId: '1:157706479340:ios:1f0136ba041d971722a7c9',
//     messagingSenderId: '157706479340',
//     projectId: 'growth-26879',
//     storageBucket: 'growth-26879.firebasestorage.app',
//     iosBundleId: 'com.example.growth',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDNhhQ-222oXE_9KPFPQj2WRAKCybJlUFw',
//     appId: '1:157706479340:web:9b7dc9a168951d1b22a7c9',
//     messagingSenderId: '157706479340',
//     projectId: 'growth-26879',
//     authDomain: 'growth-26879.firebaseapp.com',
//     storageBucket: 'growth-26879.firebasestorage.app',
//     measurementId: 'G-JMZ4DW0SJL',
//   );
// }
